name: tajweed_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  generic_requester:
    path: ../flutter_projects/generic_requester

  cg_core_defs:
    path: ../flutter_projects/cg_core_defs

  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.1.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  isar: ^3.1.0+1

dev_dependencies:
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/    
    - assets/json/
    - assets/fonts/

#= Flutter Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tajweed_ai_icon.jpg"
  min_sdk_android: 26
  remove_alpha_ios: true

#= Flutter Native Splash
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/tajweed_ai_splash.jpg
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/tajweed_ai_splash.jpg
    color: "#FFFFFF"
  web: false
    